In [1]:
import seaborn as sns
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd 
messages = pd.read_csv('SMSSpamCollection', sep='\t',
                           names=["label", "message"])

In [3]:
#Data cleaning and preprocessing
import re
import nltk

from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
corpus = []
for i in range(0, len(messages)):
    review = re.sub('[^a-zA-Z]', ' ', messages['message'][i])
    review = review.lower()
    review = review.split()
    
    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)
    
    
# Creating the Bag of Words model
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=2500)
X = cv.fit_transform(corpus).toarray()

y=pd.get_dummies(messages['label'])
y=y.iloc[:,1].values


# Train Test Split

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 0)

# Training model using Naive bayes classifier

from sklearn.naive_bayes import MultinomialNB
spam_detect_model = MultinomialNB().fit(X_train, y_train)

y_pred=spam_detect_model.predict(X_test)


In [4]:
y_pred

array([0, 1, 0, ..., 0, 1, 0], dtype=uint8)

In [5]:
y_test

array([0, 1, 0, ..., 0, 1, 0], dtype=uint8)

In [6]:
from sklearn.metrics import confusion_matrix,accuracy_score

In [7]:
confusion_m=confusion_matrix(y_test,y_pred)
confusion_m

array([[946,   9],
       [  7, 153]], dtype=int64)

In [8]:
accuracy=accuracy_score(y_test,y_pred)

In [9]:
accuracy

0.9856502242152466